# Step 1: Use official JDK base image
FROM eclipse-temurin:17-jdk-alpine

# Step 2: Set working directory inside container
WORKDIR /app

# Step 3: Copy Maven/Gradle built jar file into container
COPY target/url-shortener-1.0.0.jar app.jar

# Step 4: Expose Spring Boot default port
EXPOSE 8080

# Step 5: Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
